apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: echo-analysis
spec:
  args:
    - name: namespace
  metrics:
    - name: container-restarts
      interval: 2s
      count: 3
      successCondition: result < 1
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: |
            sum(increase(kube_pod_container_status_restarts_total{
              namespace="{{args.namespace}}",
              pod=~"echo-server-.*"
            }[1m])) or vector(0)
    - name: ready-containers
      interval: 2s
      count: 3
      successCondition: result >= 1
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: |
            # Check how many containers are ready (should be at least 1)
            # Look at kube_pod_container_status_* metrics
            # Test in Prometheus UI (port 30102 in the "Ports" tab of VS Code)


