apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hotrod
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: hotrod
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: hotrod
          image: jaegertracing/example-hotrod:1.76.0
          imagePullPolicy: IfNotPresent
          args: ["all"]
          env:
            - name: JAEGER_AGENT_HOST
              value: localhost
            - name: JAEGER_AGENT_PORT
              value: "6831"
          ports:
            - containerPort: 8080
              name: frontend
            - containerPort: 8081
              name: customer
            - containerPort: 8083
              name: route
          resources:
            limits:
              cpu: 100m
              memory: 100M
            requests:
              cpu: 100m
              memory: 100M
  strategy:
    canary:
      steps:
        - setWeight: 33
        - analysis:
            templates:
              - templateName: echo-analysis
            args:
              - name: namespace
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
        - setWeight: 66
        - analysis:
            templates:
              - templateName: echo-analysis
            args:
              - name: namespace
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
        - setWeight: 100