apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  accounts.alice: login
  ui.bannercontent: 'Challenge Instructions: GitOps Progressive Delivery with Release Telemetry' # TODO make flexible
  ui.bannerurl: "https://argoproj.github.io" # TODO make flexible
